name = "cloud-server"
main = "src/index.ts"
compatibility_date = "2023-08-23"
usage_model = "standard"
env = { }

[triggers]
crons = [ ]

[unsafe]
  [[unsafe.bindings]]
  database_id = "6ea399f6-74ea-451c-aa26-5ba1623dc619"
  name = "db"
  type = "d1"
