name = "cloud-server"
main = "src/index.js"
compatibility_date = "2023-08-23"

[[d1_databases]]
name = "cloud-server-db"
binding = "db"
database_id = "6ea399f6-74ea-451c-aa26-5ba1623dc619"


[site]
bucket = "./src/assets"